### ISSUE TITLE
Kernel Panic with AppleIntelCPUPowerManagementInfo.kext

### ISSUE THREAD

**Issue by ExPeacer** [Piker-Alpha/RevoBoot#4]
After installing AppleIntelCPUPowerManagementInfo.kext, I got a Kernel Panic, then restart. I disabled logIGPU and logMSRs.

Log here: https://gist.github.com/ExPeacer/8266581/raw/c094ca9418564b728c8a31d368687dad6e3ad15a/KPLog

System:

Intel Core i7 4770
Gigabyte Z87X-UD3H
Gigabyte 270X 2Gb

I'm using latest Clover for now, until I figure out how to build a good RevoBoot for me :)

**Comment by Piker-Alpha** [comment]
Please. Keep using Clover/Chameleon or Chimera for as long as you want. I only ask people to use RevoBoot, temporally, when they want my help with power management or other issues. Just to make it easier for me!

Have you compiled the source code from this Github repository, because your CPU is already reported to work with the latest kext.

**Comment by ExPeacer** [comment]
I tried, and it seems to work. Thanks for your help!

I have problems with power management. I can't get working SpeedStep with Clover or with any Chimera fork, that's why I started to search any other solution - and I found your work, which really impressive. If it's not problem I want to help for you, because it's good for me, too.

Closed/Solved.
